# 修改默认快捷键前缀
set -g prefix 'C-a'
bind-key 'C-a' send-prefix
unbind-key C-b

bind r source-file ~/.config/tmux/tmux.conf \; display "~/.config/tmux/tmux.conf reloaded!"

# 开启 vi 风格的快捷键
setw -g mode-keys vi # 与复制操作有关
set -g status-keys vi # 与命令操作有关

# 支持鼠标操作
setw -g mouse on

# 修改分隔窗口快捷键
bind-key = split-window -h -c "#{pane_current_path}" # 向右拆分新的pane
bind-key - split-window -v -c "#{pane_current_path}" # 向下拆分新的pane

# 设置默认的终端模式为 256 色模式
set default-terminal "tmux-256color"

# 检测焦点变化
setw -g monitor-activity on

# 启用窗口的焦点事件通知
set-option -g focus-events on

# 响应速度
set -g escape-time 5

# 开启活动通知
setw -g monitor-activity on
set -g visual-activity on

# 每 10 秒更新一次状态栏
set -g status-interval 10

# 改变window和pane的编号从1开始
set -g base-index 1
setw -g pane-base-index 1

# 在关闭之后自动按照编号重命名
set -g renumber-windows on
set -g automatic-rename on

# 如果安装了fish则默认启动
# set -g default-command "command -v fish > /dev/null 2>&1 && exec fish -l || exec bash -l"

# 设置默认shell
if-shell "[ -e ~/.local/bin/fish ]" \
    "set-option -g default-shell ~/.local/bin/fish" \
    "if-shell '[ -e /usr/bin/fish ]' \
        'set-option -g default-shell /usr/bin/fish' \
        'set-option -g default-shell /bin/bash'"


# ---------------------
# 状态栏美化
# ---------------------

# 状态栏颜色
set -g status-bg 'black'
set -g status-fg 'white'

# 右侧状态栏
set -g status-right "#[fg=green]#(whoami)@#(hostname)#[default] #[fg=green]%Y-%m-%d %H:%M " # 时间
set -g status-right-length 40

# 左侧状态栏
set -g status-left "#[fg=yellow,bold] [#S]   " # 当前session
set -g status-left-length 10

# window状态信息(left/centre/right)
set -g status-justify centre

setw -g window-status-current-format '#[fg=blue,bold]#I #[fg=blue,bold]#W#F' # 当前window
setw -g window-status-format '#[fg=white]#I #W#F' # 其它window
setw -g window-status-separator '  ' # window分隔

# 状态栏消息颜色
set -g message-style bg=blue,fg=white
